config/routes.rb
Rails.application.routes.draw do

  post 'messages' => 'messages#create', as: :messages

  get '/contact_modal/:id' => 'rolodex#modal', as: :open_contact_modal

  get 'sessions/new' => 'sessions#new', as: :sign_in
  post 'sessions' => 'sessions#create', as: :auth
  delete 'sessions' => 'sessions#destroy', as: :sign_out

  root 'rolodex#index'

  delete 'contacts/:id' => 'rolodex#destroy', as: :delete_contact

  get "admin" => 'admin#index', as: :admin
  get 'admin/new' => 'admin#new', as: :new_contact
  get 'admin/:id' => 'admin#show', as: :contact
  post 'admin' => 'admin#create', as: :contacts
  patch 'admin/:id' => 'admin#update'
  delete 'admin/:id' => 'admin#destroy'
  get 'admin/:id/edit' => 'admin#edit', as: :edit_contact

end

app/models/contact.rb
class Contact < ActiveRecord::Base

  mount_uploader :photo, AvatarUploader

  validates :first_name, :last_name, :email, :phone, :company_name, :photo, presence: true

  def full_name
    [last_name, first_name].join(", ")
  end
end

app/models/message.rb
class Message < ActiveRecord::Base

  validates :from, :email, :message, presence: true

  validates :email, format: {with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }

end

app/models/user.rb
class User < ActiveRecord::Base

  validates :username, presence: true
  has_secure_password

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController

  before_action do
    if @current_user.nil?
      redirect_to sign_in_path
    end
  end

  before_action do
    unless @current_user.admin?
      redirect_to root_path, alert: "Ya Aint Got the Access"
    end
  end

  def index
    @contacts = Contact.all.order("last_name")
  end

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new contact_params
    if @contact.save
      redirect_to admin_path
    else
      render :new
    end
  end

  def show
    @contact = Contact.find params[:id]
  end

  def edit
    @contact = Contact.find params[:id]
  end

  def update
    @contact = Contact.find params[:id]

    respond_to do |format|
      format.html do

        if @contact.update contact_params
          redirect_to contact_path(id: @contact.id)
        else
          render :edit
        end

      end

      format.js do
        @contact.update contact_params
      end
    end



  end

  def destroy
    @contact = Contact.find params[:id]
    @contact.destroy
    redirect_to admin_path
  end

  def contact_params
    params.require(:contact).permit(:first_name, :last_name, :email, :phone, :company_name, :photo)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action do
    @current_user = User.find_by id: session[:user_id]
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def create
    @message = Message.new params.require(:message).permit(:from, :email, :message)
    # if @message.save
    #   redirect_to root_path, notice: "Thanks! We'll never be in touch"
    # else
    #   redirect_to :back, alert: "Something wrong: #{@message.errors.full_messages.join(', ')}"
    # end
    @message.save
  end
end

app/controllers/rolodex_controller.rb
class RolodexController < ApplicationController
  def index
    set_contacts
    @message = Message.new
  end

  def modal
    @contact = Contact.find params[:id]
  end

  def destroy
    @contact = Contact.find params[:id]
    @contact.destroy
    set_contacts
    # redirect_to root_path, notice: '💔 Deleted 💔'
  end

  def set_contacts
    @contacts = Contact.all
                       .order('last_name')
                       .page(params[:page])

  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    username = params[:username]
    password = params[:password]

    user = User.find_by username: username
    if (user) && (user.authenticate password)
      session[:user_id] = user.id
      redirect_to admin_path
    else
      flash.now[:alert] = "Something Wrong"
      render :new
    end
  end

  def destroy
    session.delete :user_id
    redirect_to admin_path
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rolodex_helper.rb
module RolodexHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/admin/_form.html.erb
<%= simple_form_for @contact do |f| %>
  <%= f.input :first_name %>
  <%= f.input :last_name %>
  <%= f.input :email, disabled: !@contact.new_record? %>
  <%= f.input :phone %>
  <%= f.input :company_name %>
  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/admin/edit.html.erb
<%= link_to "Admin", admin_path %>

<h1>Editing <%= @contact.full_name %></h1>
<%= render partial: 'form' %>

app/views/admin/index.html.erb
<div class="pull-right">
  <%= link_to "New Contact", new_contact_path, class: 'btn btn-default' %>
</div>

<h3>Number of Contacts: <%= @contacts.count %> </h3>
<table class="table table-striped table-bordered table-hover">
  <thead>
    <tr>
      <th>Last Name</th>
      <th>First Name</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.last_name %></td>
        <td><%= contact.first_name %></td>

        <td>
          <%= link_to 'Edit', edit_contact_path(id: contact.id) %> |
          <%= link_to 'Show', contact_path(id: contact.id) %> |
          <%= link_to 'Delete', contact_path(id: contact.id), method: :delete, data: {confirm: "Ya Sure?"} %>

        </td>
      </tr>

    <% end %>
  </tbody>
</table>

app/views/admin/new.html.erb
<%= link_to "Admin", admin_path %>

<h1>New contact</h1>
<%= render partial: 'form' %>

app/views/admin/show.html.erb
<%= link_to "Admin", admin_path %>

<div class="page-header">
  <h1><%= @contact.full_name %></h1>
</div>

<div class="row">
  <div class="text-right">
    <p>
      <%= link_to "Edit", edit_contact_path(id: @contact.id), class: "btn btn-default" %>
      <%= link_to 'Delete', contact_path(id: @contact.id), class: "btn btn-danger", method: :delete, data: {confirm: "Ya Sure?"} %>
    </p>

  </div>

</div>

<dl>
  <dt>First Name</dt>
  <dd><%= @contact.first_name %></dd>
  <dt>Last Name</dt>
  <dd><%= @contact.last_name %></dd>
  <dt>Email</dt>
  <dd><%= @contact.email %></dd>
  <dt>Phone</dt>
  <dd><%= @contact.phone %></dd>
  <dt>Company</dt>
  <dd><%= @contact.company_name %></dd>
</dl>

app/views/admin/update.js.erb
<% if @contact.errors.none? %>

  alert("updated successfully");

  // Close the modal

  $("#contact-edit-<%= @contact.id %>").modal('hide');

  //var row = $("tr[data-contact-id='<%= @contact.id %>']");
  //row.find(".last_name").html('<%= j @contact.last_name %>');
  //row.find(".first_name").html('<%= j @contact.first_name %>');

  $("tr[data-contact-id='<%= @contact.id %>']").html("<%= j render partial: 'rolodex/contact_row', locals: {contact: @contact} %>");


<% else %>

  var thehtml = '<%= j render partial: 'rolodex/form', locals: {contact: @contact} %>';


  $("#contact-edit-<%= @contact.id %> .remote-contact-form").html(thehtml);
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Contacts</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if notice %>
  <div class="alert alert-info"%>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <%= notice %>
  </div>
<% end %>

<% if alert %>
  <div class="alert alert-danger"%>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <%= alert %>
  </div>
<% end %>

<div class="container">

  <% if @current_user %>
    <%= link_to "Sign Out", sign_out_path, method: :delete %>
  <% end %>

  <%= yield %>
</div>

</body>
</html>

app/views/messages/_form.html.erb
<%= simple_form_for @message, remote: true do |f| %>
  <%= f.input :from, label: 'Your Name', placeholder: 'Your name' %>
  <%= f.input :email, label: 'Your Email', placeholder: 'you@example.com' %>
  <%= f.input :message,  placeholder: "😢 or 😎 Your complaint (or compliment [LOL right?!]) goes here." %>
  <%= f.submit 'Send Message', class: "btn btn-primary btn-block" %>
<% end %>

app/views/messages/_thanks.html.erb
<div class="alert alert-success">
  <h4>Thanks!</h4>

  <p>We'll be in touch. Allegedly.</p>
</div>

app/views/messages/create.js.erb
// If valid
//   say thanks
// else
//   render form

<% if @message.errors.none? %>

  var thehtml = '<%= j render partial: 'messages/thanks' %>';

  $("#contact-form").html(thehtml);


<% else %>

  var thehtml = '<%= j render partial: 'messages/form' %>';

  $("#contact-form").html(thehtml);
<% end %>

app/views/rolodex/_contact_row.html.erb
  <td><%= image_tag contact.photo.url(:thumb) %></td>
  <td><%= contact.last_name %></td>
  <td><%= contact.first_name %></td>

  <td>

    <%= link_to 'View Details',
                open_contact_modal_path(id: contact.id),
                remote: true,
                class: 'btn btn-default'
    %>


    <% if @current_user.nil? %>

      <%= link_to 'Sign In To Edit', sign_in_path %>

    <% else %>

      <button type="button" class="btn btn-default" data-toggle="modal" data-target="#contact-edit-<%= contact.id %>">
        Edit
      </button>

      <%= link_to 'Delete', delete_contact_path(id: contact.id, page: params[:page]), method: :delete, data: {confirm: "Are you sure?"}, remote: true, class: 'btn btn-danger contact-delete' %>


    <% end %>
  </td>

<!-- Modal -->
<div class="modal fade" id="contact-edit-<%= contact.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Editing <%= contact.full_name %></h4>
      </div>
      <div class="modal-body">
        <div class="remote-contact-form">
          <%= render partial: 'rolodex/form', locals: {contact: contact} %>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/rolodex/_contacts.html.erb
<h3>Number of Contacts: <%= @contacts.total_count %> </h3>
<table class="table table-striped table-bordered table-hover">
  <thead>
    <tr>
      <th>Photo</th>
      <th>Last Name</th>
      <th>First Name</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @contacts.each do |contact| %>
      <tr data-contact-id="<%= contact.id %>">
        <%= render partial: 'contact_row', locals: {contact: contact} %>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @contacts %>

<!-- Modal -->
<div class="modal fade" id="contact-detail" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      {{ stuff goes here, eventually }}
    </div>
  </div>
</div>

app/views/rolodex/_form.html.erb
<%= simple_form_for contact, remote: true do |f| %>
  <%= f.input :first_name %>
  <%= f.input :last_name %>
  <%= f.input :email, disabled: !contact.new_record? %>
  <%= f.input :phone %>
  <%= f.input :photo %>
  <%= f.input :company_name %>
  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/rolodex/_modal_content.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  <h4 class="modal-title" id="myModalLabel"><%= contact.last_name %>, <%= contact.first_name %></h4>
</div>
<div class="modal-body">
  <ul>
    <li><strong>Phone</strong>: <%= link_to contact.phone, "tel:#{contact.phone}" %></li>
    <li><strong>Email</strong>: <%= mail_to contact.email %></li>
    <li><strong>Company</strong>: <%= contact.company_name %></li>
  </ul>
</div>
<div class="modal-footer">
  <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
</div>

app/views/rolodex/destroy.js.erb
// console.log("Yo there");
// alert("Oh hai!");

// $(this).closest("tr").hide("slow");

$("tr[data-contact-id='<%= @contact.id %>']").hide("slow");

$("#contacts").html("<%= j render partial: 'contacts' %>");

app/views/rolodex/index.html.erb
<div class="page-header">
  <h1>Rollodex <small>like it's 1975</small></h1>
</div>

<div class="row">
  <div class="col-md-8">
    <div id="contacts">
      <%= render partial: 'contacts' %>
    </div>
  </div>
  <div class="col-md-4">
    <h3>Contact Us</h3>

    <div id="contact-form">
      <%= render partial: 'messages/form' %>
    </div>

  </div>
</div>

app/views/rolodex/modal.js.erb
// Render some deets into the modal

$("#contact-detail .modal-content").html("<%= j render partial: 'rolodex/modal_content', locals: {contact: @contact} %>");

// Open a modal

$("#contact-detail").modal('show');